theme: jekyll-theme-minimal
title: Florian Beutler\\![Image of Florian Beutler](https://avatars0.githubusercontent.com/u/10950512?v=4&u=95429ac36ffcd5986631a2e1fad2eec873adc027&s=400)
description: Here I provide some information on ideas and projects I work on. 
